### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by pinkponk** [netrasys/pgANN#4]
Nice to find a ANN which is not RAM based! Thanks!!

Just tried this with **50 000 000 entries** of **length 90**. Size of the table is with the embeddings 38Gb. Used postgres in a container and ran a search for a single random embedding with:

`sql = "select id,embeddings from images order by embeddings <-> cube({0}) asc limit 25".format((emb_string))`

This search took **230s**. I have very good cpu and memory speeds on this computer.  **I'm I doing something wrong or is this reasonable?**

My issue is this: the total size of the table was about 38Gb which means it sort of fits in RAM. Is it better to use faiss? If I double the db size will it take double the time?

**Comment by pinkponk** [comment]
Did some more testing:
All test done with length 90 with the average duration of 100 test queries. query is to take the 25 nearest neighbors. These tests are not very scientific so don't trust the numbers so much.

postgres: (not much cpu action)
5 000 000 entries: 1.25s
10 000 000 entries: 2.39s
50 000 000 entries: 230s

annoy: (single core at 100%)
50 000 000 entries: 0.001s ish (takes almost no RAM!!! index on disk.)

ScAnn: (all cpu cores at 100%)
20 000 000 entries: 0.001s ish
50 000 000 entries: 0.002s ish (**takes 100Gb RAM!!!**) (from 100GB there is 32Gb M2 disk as swap 3000mb/s ish transfer speeds)

Either I'm doing something very wrong or there is not use for postgres for large datasets. I would love to use posgres and to be able to add embeddings on the fly while updating the index but for my case it is to slow.

**Comment by shashi-netra** [comment]
Hi, I'm sorry you are having trouble using `pgANN` for your need. Here are some steps I would suggest trying further to improve query performance:

- reduce dimensionality (using `UMAP`, or <insert your favorite approach>) and using that as an embedding
- `horizontal partitioning` data across multiple tables and using `parallelism` to combine results

In both cases, you will need to fetch a significant `N` from the DB query and then `re-rank` based on your favorite similarity metric. 

Unfortunately, there are no easy wins in ANN approaches, and our frustration with the in-memory approaches led us to come up with this hack. While it might not scale to hundreds of millions of rows, it seems to serve our needs well. 

Hope the suggestions are helpful. BTW there have been a few ANN libraries announced outside of FAISS/Annoy: MILVUS, something from Microsoft (can't recall the name), I haven't tried them. But it's still an under-served field in AI, unfortunately :-(

**Comment by shashi-netra** [comment]
BTW if you come up with a better approach please do share, or if you figure out a better way of using pgANN at scale, please submit a pull request. Thanks for your interest and kind words.

**Comment by pinkponk** [comment]
Big thanks for your quick answer! 

A lot of good tips for me to try! 

I'm going to try milvus, seems that I missed milvus during my google searches so thanks for the tip!

Milvus seems to be an umbrella system which uses algorithms from faiss/annoy and many more. There seems to be some index handling which could be excactly what I need.
