### ISSUE TITLE
Worse performance with GIST?

### ISSUE THREAD

**Issue by dventimi** [netrasys/pgANN#6]
Hey!  This is really great, and I want to thank you for looking into using PostgreSQL cube data types and GIST indexes for nearest neighbor queries.  I did want to ask you, though, did you ever run into any issues where the GIST index actually made performance _worse_?  The reason I ask is, I seem to be experiencing that.  It's all documented in this StackOverflow [question](https://stackoverflow.com/questions/67337300/why-does-a-gist-index-on-a-cube-column-in-postgresql-actually-make-k-nearest-nei?noredirect=1#comment119025837_67337300) and also in a related GitHub [repo](https://github.com/dventimi/pgnns).  I'm still researching the problem, but my working theory right now is that, without the index postgres will do a parallel sequential scan on the table, whereas with the index it'll only do a sequential scan of the index.  If that's true, then I'm trying to figure out how to coax it into doing a parallel index scan if at all.  Will update you as I progress!

**Comment by shashi-netra** [comment]
Hi, thanks for your post, and happy you found it useful. Unfortunately, I am not too versed in the GIST index to offer any ideas but would love to know what you find out.

**Comment by dventimi** [comment]
You bet!  Will do.
